title = "Objektinis programavimas I (P175B118)"

student = { name = "Studento Emiljaus Paulausko IF-1/1", gender = "male" }
lecturer = { name = "lekt. Alice Alison", gender = "female" }

tests_folder = "tests"

[[sections]]
title = "Paveldejimas"
project = "Lab5"
problem = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
* raskite skaiciu 55.
* raskite kazka
* blah blah
Tekstas po punktu
"""

